### ISSUE TITLE
Auth failure

### ISSUE THREAD

**Issue by davidedmundson** [tiagosh/libhangish#2]
I have two accounts, one normal; one complex. The simple one works, the latter doesn't.

On the account that fails: 
I have two factor auth
I have apps for my domain (i.e me@mysite.co.uk)

When I sign in I get into the branch                     //Something went wrong  in Authenticator::networkCallback

I get redirected to a URL which doesn't start with "https://accounts.google.com/SecondFactor" (SECONDFACTOR_URL)

full debug logs

sendCredentials
end network callback
networkCallback 2
redirected QUrl("https://accounts.google.com/signin/challenge?continue=https%3A%2F%2Ftalkgadget.google.com%2Ftalkgadget%2Fgauth%3Fverify%3Dtrue&checkedDomains=youtube&pstMsg=0&skipvpage=true")
end network callback
networkCallback 2
Auth failed  QUrl("https://accounts.google.com/signin/challenge?continue=https%3A%2F%2Ftalkgadget.google.com%2Ftalkgadget%2Fgauth%3Fverify%3Dtrue&checkedDomains=youtube&pstMsg=0&skipvpage=true")

Let me know what I can do to help debug + fix.

**Comment by tiagosh** [comment]
Thanks for the report and debug.
I believe I fixed this in trunk already. Please, also update telepathy-hanging as I needed to change the name of one api method.

**Comment by davidedmundson** [comment]
Yeah, connected now. Thanks
