### ISSUE TITLE
Join forces

### ISSUE THREAD

**Issue by alexandernst** [tiagosh/libhangish#4]
There is another project implementing Hangouts proto that seems to manage quite some features. Maybe join forces? https://github.com/tdryer/hangups

**Comment by tiagosh** [comment]
Hello,

hangups is a nice project, but it's unfortunately written in python. libhangish was originally developed to be used in telepathy-hanging, which is written in c++. We can obviously share our finding about the protocol, but not much more at the moment. 

Thank you anyway.
